# Generated by Django 3.1.7 on 2021-04-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NFTs',
            new_name='Post',
        ),
    ]
