# Generated by Django 3.1.7 on 2021-04-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0005_auto_20210412_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
