# Generated by Django 3.1.7 on 2021-04-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0006_auto_20210412_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sold',
            field=models.BooleanField(),
        ),
    ]
